[package]
name = "cx-pipeline-data"
version = "0.0.0"
edition = "2024"

[features]
default = []
test = []

[dependencies]
speedy = { version = "0.8.7" }

cx-tokens = { path = "../cx-tokens" }
cx-ast  = { path = "../cx-ast" }
cx-mir = { path = "../cx-mir" }
cx-lmir = { path = "../cx-lmir" }
