[package]
name = "cx-lsp"
version = "0.0.0"
edition = "2021"

[dependencies]
tower-lsp = "0.20"
tokio = { version = "1.48.0", features = ["full"] }
dashmap = "5.5"

cx-lexer = { path = "../cx-lexer" }
cx-lexer-data = { path = "../cx-lexer-data" }
