[package]
name = "cx-mir"
version = "0.0.0"
edition = "2024"

[dependencies]
speedy = "0.8.7"

cx-ast = { path = "../cx-ast" }
cx-util = { path = "../cx-util" }

uuid = { version = "1.17.0", features = ["v4"] }
