[package]
name = "cx-mir"
version = "0.1.0"
edition = "2024"

[dependencies]
cx-util = { path = "../cx-util" }

cx-parsing-data = { path = "../cx-parsing-data" }
cx-mir-data = { path = "../cx-mir-data" }
cx-typechecker-data = { path = "../cx-typechecker-data" }