[package]
name = "cx-lexer"
version = "0.0.0"
edition = "2024"

[dependencies]
cx-tokens = { path = "../cx-tokens" }
cx-pipeline-data = { path = "../cx-pipeline-data" }

cx-util = { path = "../cx-util" }
